test local branch

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -1,17 +1,38 @@
 name: PR Test operator
 
 on:
-  pull_request:
-    branches: 
-    - main
-    - rhdh-1.[0-9]+
-    - 1.[0-9]+.x
-    - release-1.[0-9]+
+  pull_request_target:
+      types: [opened, synchronize, reopened, ready_for_review]
+      branches: 
+      - main
+      # - rhdh-1.[0-9]+
+      # - 1.[0-9]+.x
+      # - release-1.[0-9]+
 jobs:
+  authorize:
+    # The 'external' environment is configured with the odo-maintainers team as required reviewers.
+    # All the subsequent jobs in this workflow 'need' this job, which will require manual approval for PRs coming from external forks.
+    # see list of approvers in OWNERS file
+    environment:
+      ${{ (github.event.pull_request.head.repo.full_name == github.repository ||
+        contains(fromJSON('["gazarenkov","nickboldt","rm3l","openshift-cherrypick-robot"]'), github.actor)) && 'internal' || 'external' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: approved
+        run: |
+          echo "✓"
+
   pr-validate:
     name: PR Validate
     runs-on: ubuntu-latest
+    needs: authorize
     steps:
+      - name: Handle invalid context for pull requests
+        if: ${{ (!github.event.pull_request.head.sha || !github.event.pull_request.number) }}
+        run: |
+          echo "[ERROR] Pull Request has no github.event.pull_request.head.sha or github.event.pull_request.number: must exit."
+          exit 1
+          
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
         with:
@@ -48,18 +69,71 @@ jobs:
         with:
           go-version-file: 'go.mod'
 
+      - name: Store build timestamp
+        run: echo "BUILD_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
+
+      - name: Write SeaLights token into file
+        if: steps.changed-files.outputs.any_changed == 'false'
+        run: echo "${SEALIGHTS_AGENT_TOKEN}" > sltoken.txt
+        env:
+          SEALIGHTS_AGENT_TOKEN: '${{secrets.SEALIGHTS_AGENT_TOKEN}}' ## Make sure to add token to repo secrets
+
+      - name: Download SeaLights Go agent and CLI tool
+        if: steps.changed-files.outputs.any_changed == 'false'
+        run: |
+            echo "[SeaLights] Downloading SeaLights Golang & CLI Agents..."
+            # Architectures available: darwin-amd64, darwin-arm64, linux-amd64, linux-arm64
+            SL_OS_ARCH=linux-amd64
+            SL_GO_AGENT_VERSION=v1.1.195
+            SL_CLI_AGENT_VERSION=v1.0.49
+
+            wget -nv -O sealights-go-agent.tar.gz https://agents.sealights.co/slgoagent/${SL_GO_AGENT_VERSION}/slgoagent-${SL_OS_ARCH}.tar.gz
+            wget -nv -O sealights-slcli.tar.gz https://agents.sealights.co/slcli/${SL_CLI_AGENT_VERSION}/slcli-${SL_OS_ARCH}.tar.gz
+
+            tar -xzf ./sealights-go-agent.tar.gz && tar -xzf ./sealights-slcli.tar.gz 
+            rm -f ./sealights-go-agent.tar.gz ./sealights-slcli.tar.gz 
+            ./slgoagent -v 2> /dev/null | grep version && ./slcli -v 2> /dev/null | grep version
+
+      - name: Initiating the SeaLights agent
+        if: steps.changed-files.outputs.any_changed == 'false'
+        run: |
+          echo "[SeaLights] Initiating the SeaLights agent to Golang and handing it the token"
+          ./slcli config init --lang go --token ./sltoken.txt
+
+      - name: Configuring SeaLights
+        if: steps.changed-files.outputs.any_changed == 'false'
+        run: |
+          echo "[SeaLights] Configuring SeaLights to scan the pull request branch"
+          echo "Latest commit sha: ${LATEST_COMMIT_SHA}"
+          echo "PR Number: ${PULL_REQUEST_NUMBER}"
+          echo "Target Branch: ${TARGET_BRANCH}"
+          echo "REPO_URL: ${REPO_URL}"
+          ./slcli config create-pr-bsid --app rhdh-operator --target-branch ${TARGET_BRANCH} --pull-request-number ${PULL_REQUEST_NUMBER} --latest-commit ${LATEST_COMMIT_SHA} --repository-url https://github.com/npotluri-rh/rhdh-operator.git
+        env:
+          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
+          LATEST_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
+          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }} #github.event.pull_request.base.ref # github.base_ref 
+          REPO_URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
+
+      - name: Run SeaLights scan for tests
+        if: steps.changed-files.outputs.any_changed == 'false'
+        run: |
+          echo "[SeaLights] Running the SeaLights scan"
+          ./slcli scan --bsid buildSessionId.txt  --path-to-scanner ./slgoagent --workspacepath "./" --scm git --scmBaseUrl https://github.com/npotluri-rh/rhdh-operator --scmProvider github
+# SEALIGHTS_LAB_ID
+          
       # gosec needs a "build" stage so connect it to the lint step which we always do
       - name: Build
         run: make lint
 
       - name: Start Minikube
         # run this stage only if there are changes that match the includes and not the excludes
-        if: steps.changed-files.outputs.any_changed == 'true'
+        if: steps.changed-files.outputs.any_changed == 'false'
         uses: medyagh/setup-minikube@cea33675329b799adccc9526aa5daccc26cd5052 # v0.0.19
 
       - name: Run Controller
         # run this stage only if there are changes that match the includes and not the excludes
-        if: steps.changed-files.outputs.any_changed == 'true'
+        if: steps.changed-files.outputs.any_changed == 'false'
         run: |
           # Need to 'make install' first, so that the necessary tool binaries (like controller-gen) can be downloaded locally.
           # Otherwise, we might end up with a race condition where the tool binary is not yet downloaded,
@@ -69,19 +143,25 @@ jobs:
 
       - name: Test
         # run this stage only if there are changes that match the includes and not the excludes
-        if: steps.changed-files.outputs.any_changed == 'true'
+        if: steps.changed-files.outputs.any_changed == 'false'
         run: make test
 
       - name: Generic Integration test
         # run this stage only if there are changes that match the includes and not the excludes
         # perform it on backstage.io for speed
-        if: steps.changed-files.outputs.any_changed == 'true'
+        if: steps.changed-files.outputs.any_changed == 'false'
         run: make integration-test PROFILE=backstage.io USE_EXISTING_CLUSTER=true USE_EXISTING_CONTROLLER=true
 
       - name: RHDH specific Integration test
         # run this stage only if there are changes that match the includes and not the excludes
-        if: steps.changed-files.outputs.any_changed == 'true'
+        if: steps.changed-files.outputs.any_changed == 'false'
         run: make integration-test ARGS='--focus "create default rhdh"' USE_EXISTING_CLUSTER=true USE_EXISTING_CONTROLLER=true
+
+      - name: Clean all SeaLights secret stuff
+        if: always() && steps.changed-files.outputs.any_changed == 'false'
+        run: |
+          echo "[SeaLights] Cleaning up after SeaLights run"
+          rm sltoken.txt
 
       - name: Run Gosec Security Scanner
         run: make gosec
